name: Build Mesen

on: [push, workflow_dispatch]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  windows:
    strategy:
      matrix:
        platform: [
          {netversion: 10.x, targetframework: net10.0, aot: false, singleFile: true, aotString: ""},
          {netversion: 10.x, targetframework: net10.0, aot: true, singleFile: false, aotString: " - AoT"}
        ]
      fail-fast: false
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.platform.netversion }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Restore packages
        run: dotnet restore -p:TargetFramework="${{ matrix.platform.targetframework }}" -r win-x64 -p:PublishAot="${{ matrix.platform.aot }}" -p:BuildWithNetFrameworkHostedCompiler=true

      - name: Write commit SHA1 to file
        uses: ./.github/actions/build-sha1-action

      - name: Build Mesen
        run: msbuild -nologo -v:d -clp:ForceConsoleColor -m -p:Configuration=Release -p:Platform=x64 -t:Clean,UI -p:TargetFramework="${{ matrix.platform.targetframework }}" -p:OptimizeUi="true"

      - name: Publish Mesen
        run: dotnet publish --no-restore -c Release -p:PublishAot="${{ matrix.platform.aot }}" -p:SelfContained="${{ matrix.platform.aot }}" -p:PublishSingleFile="${{ matrix.platform.singleFile }}" -p:OptimizeUi="true" -p:Platform="Any CPU" -p:TargetFramework="${{ matrix.platform.targetframework }}" -r win-x64 Mesen.sln /p:PublishProfile=UI\Properties\PublishProfiles\Release.pubxml

      - name: Upload Mesen
        uses: actions/upload-artifact@v7
        with:
          name: Mesen (Windows - ${{ matrix.platform.targetframework }}${{ matrix.platform.aotString }})
          path: |
            build/TmpReleaseBuild/Mesen.exe
